config/routes.rb
Rails.application.routes.draw do
  root "dashboards#show"

  resource :session
  resources :passwords, param: :token

  resources :categories, only: %i[index new create edit update destroy]
  resources :accounts, only: %i[index new create edit update destroy]
  resources :transactions, only: %i[index new create edit update destroy]
  resources :imports, only: %i[index new create]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[edit update destroy]

  def index
    @page, @transactions = pagy(Current.user.transactions.includes(:account, :category).order(date: :desc, id: :asc), limit: 250)
  end

  def new
    @transaction = Current.user.transactions.build
  end

  def create
    @transaction = Current.user.transactions.build(transaction_params)

    if @transaction.record
      redirect_to transactions_path, notice: "Category created successfully!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @transaction.modify(transaction_params)
      redirect_to transactions_path, notice: "Category updated successfully!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @transaction.remove!

    redirect_to transactions_path, notice: "Category deleted successfully!"
  end

  private

  def transaction_params
    params.require(:transaction).permit(:date, :name, :description, :amount).merge({ account:, category: }.compact)
  end

  def account
    Current.user.accounts.find_by(id: params.dig(:transaction, :account_id))
  end

  def category
    Current.user.categories.find_by(id: params.dig(:transaction, :category_id))
  end

  def set_transaction
    @transaction = Current.user.transactions.find(params[:id])
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_with model: transaction do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div>
    <%= f.label :date %>
    <%= f.date_field :date %>
  </div>

  <div>
    <%= f.label :amount %>
    <%= f.text_field :amount %>
  </div>

  <div>
    <%= f.label :account_id %>
    <%= f.collection_select :account_id, Current.user.accounts, :id, :name, include_blank: true %>
  </div>

  <div>
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Current.user.categories, :id, :name, include_blank: true %>
  </div>

  <%= f.submit "Save" %>
<% end %>

app/views/transactions/_transaction.html.erb
<tr>
  <td><%= transaction.name %></td>
  <td><%= transaction.description %></td>
  <td><%= transaction.date %></td>
  <td><%= number_to_currency transaction.amount %></td>
  <td><%= transaction.account.name %></td>
  <td><%= transaction.category&.name || "Uncategorized" %></td>
  <td>
    <%= link_to "edit", edit_transaction_path(transaction) %>
    <%= button_to "delete", transaction_path(transaction), method: :delete %>
  </td>
</tr>

app/views/transactions/edit.html.erb
<h1>Edit transaction</h1>

<%= render "transactions/form", transaction: @transaction %>

app/views/transactions/index.html.erb
<h1>Transactions</h1>

<%= link_to "Add transaction", new_transaction_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Date</th>
      <th>Amount</th>
      <th>Account</th>
      <th>Category</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <%= render @transactions %>
  </tbody>
</table>

<% if @page.prev %>
  <%= link_to "Previous page", transactions_path(page: @page.prev) %>
<% end %>

<% if @page.next %>
  <%= link_to "Next page", transactions_path(page: @page.next) %>
<% end %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<%= render "transactions/form", transaction: @transaction %>