config/routes.rb
Rails.application.routes.draw do
  root "dashboards#show"

  resource :session
  resources :passwords, param: :token

  resources :categories, only: %i[index new create edit update destroy]
  resources :accounts, only: %i[index new create edit update destroy]
  resources :transactions, only: %i[index new create edit update destroy]
  resources :imports, only: %i[index new create]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Moneyonrails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/views/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <%= link_to "Dashboard", root_path %>
      <%= link_to "Transactions", transactions_path %>
      <%= link_to "Accounts", accounts_path %>
      <%= link_to "Categories", categories_path %>
      <%= link_to "Imports", imports_path %>
    </header>

    <% flash.each do |type, message| %>
      <div>
        <%= message %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>