config/routes.rb
Rails.application.routes.draw do
  root "dashboards#show"

  resource :session
  resources :passwords, param: :token

  resources :categories, only: %i[index new create edit update destroy]
  resources :accounts, only: %i[index new create edit update destroy]
  resources :transactions, only: %i[index new create edit update destroy]
  resources :imports, only: %i[index new create]

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/account.rb
class Account < ApplicationRecord
  has_many :transactions, dependent: :destroy
  belongs_to :user

  validates :name, :balance, presence: true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[edit update destroy]

  def index
    @accounts = Current.user.accounts
  end

  def new
    @account = Current.user.accounts.build
  end

  def create
    @account = Current.user.accounts.build(account_params)

    if @account.save
      redirect_to accounts_path, notice: "Account created successfully!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @account.update(account_params)
      redirect_to accounts_path, notice: "Account updated successfully!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @account.destroy!

    redirect_to accounts_path, notice: "Account deleted successfully!"
  end

  private

  def account_params
    params.require(:account).permit(:name, :balance)
  end

  def set_account
    @account = Current.user.accounts.find(params[:id])
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_account.html.erb
<tr>
  <td><%= account.name %></td>
  <td><%= number_to_currency account.balance %></td>
  <td>
    <%= link_to "edit", edit_account_path(account) %>
    <%= button_to "delete", account_path(account), method: :delete %>
  </td>
</tr>

app/views/accounts/_form.html.erb
<%= form_with model: account do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div>
    <%= f.label :balance %>
    <%= f.text_field :balance %>
  </div>

  <%= f.submit "Save" %>
<% end %>

app/views/accounts/edit.html.erb
<h1>Edit account</h1>

<%= render "accounts/form", account: @account %>

app/views/accounts/index.html.erb
<h1>Accounts</h1>

<%= link_to "Add account", new_account_path %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Balance</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <%= render @accounts %>
  </tbody>
</table>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render "accounts/form", account: @account %>